[PHP]
extension_dir = "d:/laragon/bin/php/php-8.3.30-Win32-vs16-x64/ext"

extension=curl
extension=fileinfo
extension=gd
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

memory_limit = 512M
